/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LaboratorioRouteImport } from './routes/laboratorio'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaboratorioEmgRouteImport } from './routes/laboratorio/emg'
import { Route as LaboratorioEegRouteImport } from './routes/laboratorio/eeg'
import { Route as LaboratorioEcgRouteImport } from './routes/laboratorio/ecg'

const LaboratorioRoute = LaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratorioEmgRoute = LaboratorioEmgRouteImport.update({
  id: '/emg',
  path: '/emg',
  getParentRoute: () => LaboratorioRoute,
} as any)
const LaboratorioEegRoute = LaboratorioEegRouteImport.update({
  id: '/eeg',
  path: '/eeg',
  getParentRoute: () => LaboratorioRoute,
} as any)
const LaboratorioEcgRoute = LaboratorioEcgRouteImport.update({
  id: '/ecg',
  path: '/ecg',
  getParentRoute: () => LaboratorioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/laboratorio': typeof LaboratorioRouteWithChildren
  '/laboratorio/ecg': typeof LaboratorioEcgRoute
  '/laboratorio/eeg': typeof LaboratorioEegRoute
  '/laboratorio/emg': typeof LaboratorioEmgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/laboratorio': typeof LaboratorioRouteWithChildren
  '/laboratorio/ecg': typeof LaboratorioEcgRoute
  '/laboratorio/eeg': typeof LaboratorioEegRoute
  '/laboratorio/emg': typeof LaboratorioEmgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/laboratorio': typeof LaboratorioRouteWithChildren
  '/laboratorio/ecg': typeof LaboratorioEcgRoute
  '/laboratorio/eeg': typeof LaboratorioEegRoute
  '/laboratorio/emg': typeof LaboratorioEmgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/laboratorio'
    | '/laboratorio/ecg'
    | '/laboratorio/eeg'
    | '/laboratorio/emg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/laboratorio'
    | '/laboratorio/ecg'
    | '/laboratorio/eeg'
    | '/laboratorio/emg'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/laboratorio'
    | '/laboratorio/ecg'
    | '/laboratorio/eeg'
    | '/laboratorio/emg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LaboratorioRoute: typeof LaboratorioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/laboratorio': {
      id: '/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof LaboratorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratorio/emg': {
      id: '/laboratorio/emg'
      path: '/emg'
      fullPath: '/laboratorio/emg'
      preLoaderRoute: typeof LaboratorioEmgRouteImport
      parentRoute: typeof LaboratorioRoute
    }
    '/laboratorio/eeg': {
      id: '/laboratorio/eeg'
      path: '/eeg'
      fullPath: '/laboratorio/eeg'
      preLoaderRoute: typeof LaboratorioEegRouteImport
      parentRoute: typeof LaboratorioRoute
    }
    '/laboratorio/ecg': {
      id: '/laboratorio/ecg'
      path: '/ecg'
      fullPath: '/laboratorio/ecg'
      preLoaderRoute: typeof LaboratorioEcgRouteImport
      parentRoute: typeof LaboratorioRoute
    }
  }
}

interface LaboratorioRouteChildren {
  LaboratorioEcgRoute: typeof LaboratorioEcgRoute
  LaboratorioEegRoute: typeof LaboratorioEegRoute
  LaboratorioEmgRoute: typeof LaboratorioEmgRoute
}

const LaboratorioRouteChildren: LaboratorioRouteChildren = {
  LaboratorioEcgRoute: LaboratorioEcgRoute,
  LaboratorioEegRoute: LaboratorioEegRoute,
  LaboratorioEmgRoute: LaboratorioEmgRoute,
}

const LaboratorioRouteWithChildren = LaboratorioRoute._addFileChildren(
  LaboratorioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LaboratorioRoute: LaboratorioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
